version: '3.1'
services:
   wordpress:
      image: wordpress
      restart: always
      ports:
         - 8080:80
      volumes:
         - .:/var/www/html
      environment:
         WORDPRESS_DB_PASSWORD: "${wp_password}"
